################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_bcc.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_stk.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_stk_leds.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/display.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/displayls013b7dh03.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/displaypalemlib.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/dmactrl.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/dmadrv/src/dmadrv.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/dmd/display/dmd_display.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_bitmap.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_narrow_6x8.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_normal_8x8.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_line.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_rectangle.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_string.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/uartdrv/src/uartdrv.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/udelay.c 

OBJS += \
./rangetest-base/bsp_bcc.o \
./rangetest-base/bsp_stk.o \
./rangetest-base/bsp_stk_leds.o \
./rangetest-base/display.o \
./rangetest-base/displayls013b7dh03.o \
./rangetest-base/displaypalemlib.o \
./rangetest-base/dmactrl.o \
./rangetest-base/dmadrv.o \
./rangetest-base/dmd_display.o \
./rangetest-base/glib.o \
./rangetest-base/glib_bitmap.o \
./rangetest-base/glib_font_narrow_6x8.o \
./rangetest-base/glib_font_normal_8x8.o \
./rangetest-base/glib_line.o \
./rangetest-base/glib_rectangle.o \
./rangetest-base/glib_string.o \
./rangetest-base/uartdrv.o \
./rangetest-base/udelay.o 

C_DEPS += \
./rangetest-base/bsp_bcc.d \
./rangetest-base/bsp_stk.d \
./rangetest-base/bsp_stk_leds.d \
./rangetest-base/display.d \
./rangetest-base/displayls013b7dh03.d \
./rangetest-base/displaypalemlib.d \
./rangetest-base/dmactrl.d \
./rangetest-base/dmadrv.d \
./rangetest-base/dmd_display.d \
./rangetest-base/glib.d \
./rangetest-base/glib_bitmap.d \
./rangetest-base/glib_font_narrow_6x8.d \
./rangetest-base/glib_font_normal_8x8.d \
./rangetest-base/glib_line.d \
./rangetest-base/glib_rectangle.d \
./rangetest-base/glib_string.d \
./rangetest-base/uartdrv.d \
./rangetest-base/udelay.d 


# Each subdirectory must supply rules for building sources it contributes
rangetest-base/bsp_bcc.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_bcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/bsp_bcc.d" -MT"rangetest-base/bsp_bcc.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/bsp_stk.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_stk.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/bsp_stk.d" -MT"rangetest-base/bsp_stk.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/bsp_stk_leds.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_stk_leds.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/bsp_stk_leds.d" -MT"rangetest-base/bsp_stk_leds.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/display.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/display.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/display.d" -MT"rangetest-base/display.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/displayls013b7dh03.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/displayls013b7dh03.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/displayls013b7dh03.d" -MT"rangetest-base/displayls013b7dh03.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/displaypalemlib.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/displaypalemlib.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/displaypalemlib.d" -MT"rangetest-base/displaypalemlib.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/dmactrl.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/dmactrl.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/dmactrl.d" -MT"rangetest-base/dmactrl.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/dmadrv.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/dmadrv/src/dmadrv.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/dmadrv.d" -MT"rangetest-base/dmadrv.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/dmd_display.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/dmd/display/dmd_display.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/dmd_display.d" -MT"rangetest-base/dmd_display.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/glib.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/glib.d" -MT"rangetest-base/glib.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/glib_bitmap.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_bitmap.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/glib_bitmap.d" -MT"rangetest-base/glib_bitmap.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/glib_font_narrow_6x8.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_narrow_6x8.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/glib_font_narrow_6x8.d" -MT"rangetest-base/glib_font_narrow_6x8.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/glib_font_normal_8x8.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_normal_8x8.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/glib_font_normal_8x8.d" -MT"rangetest-base/glib_font_normal_8x8.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/glib_line.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_line.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/glib_line.d" -MT"rangetest-base/glib_line.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/glib_rectangle.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_rectangle.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/glib_rectangle.d" -MT"rangetest-base/glib_rectangle.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/glib_string.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_string.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/glib_string.d" -MT"rangetest-base/glib_string.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/uartdrv.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/uartdrv/src/uartdrv.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/uartdrv.d" -MT"rangetest-base/uartdrv.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rangetest-base/udelay.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/udelay.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"rangetest-base/udelay.d" -MT"rangetest-base/udelay.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


