################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_trace.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_assert.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_cmu.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_emu.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_gpio.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_int.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_ldma.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_leuart.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rmu.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rtc.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rtcc.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_system.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_timer.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_usart.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/gpiointerrupt/src/gpiointerrupt.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/hal/hal_common.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/hal/efr32/hal_efr.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/retargetio.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/retargetserial.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/rtcdrv/src/rtcdriver.c \
C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/ustimer/src/ustimer.c 

OBJS += \
./hal-efr32/bsp_trace.o \
./hal-efr32/em_assert.o \
./hal-efr32/em_cmu.o \
./hal-efr32/em_emu.o \
./hal-efr32/em_gpio.o \
./hal-efr32/em_int.o \
./hal-efr32/em_ldma.o \
./hal-efr32/em_leuart.o \
./hal-efr32/em_rmu.o \
./hal-efr32/em_rtc.o \
./hal-efr32/em_rtcc.o \
./hal-efr32/em_system.o \
./hal-efr32/em_timer.o \
./hal-efr32/em_usart.o \
./hal-efr32/gpiointerrupt.o \
./hal-efr32/hal_common.o \
./hal-efr32/hal_efr.o \
./hal-efr32/retargetio.o \
./hal-efr32/retargetserial.o \
./hal-efr32/rtcdriver.o \
./hal-efr32/ustimer.o 

C_DEPS += \
./hal-efr32/bsp_trace.d \
./hal-efr32/em_assert.d \
./hal-efr32/em_cmu.d \
./hal-efr32/em_emu.d \
./hal-efr32/em_gpio.d \
./hal-efr32/em_int.d \
./hal-efr32/em_ldma.d \
./hal-efr32/em_leuart.d \
./hal-efr32/em_rmu.d \
./hal-efr32/em_rtc.d \
./hal-efr32/em_rtcc.d \
./hal-efr32/em_system.d \
./hal-efr32/em_timer.d \
./hal-efr32/em_usart.d \
./hal-efr32/gpiointerrupt.d \
./hal-efr32/hal_common.d \
./hal-efr32/hal_efr.d \
./hal-efr32/retargetio.d \
./hal-efr32/retargetserial.d \
./hal-efr32/rtcdriver.d \
./hal-efr32/ustimer.d 


# Each subdirectory must supply rules for building sources it contributes
hal-efr32/bsp_trace.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_trace.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/bsp_trace.d" -MT"hal-efr32/bsp_trace.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_assert.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_assert.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_assert.d" -MT"hal-efr32/em_assert.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_cmu.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_cmu.d" -MT"hal-efr32/em_cmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_emu.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_emu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_emu.d" -MT"hal-efr32/em_emu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_gpio.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_gpio.d" -MT"hal-efr32/em_gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_int.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_int.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_int.d" -MT"hal-efr32/em_int.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_ldma.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_ldma.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_ldma.d" -MT"hal-efr32/em_ldma.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_leuart.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_leuart.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_leuart.d" -MT"hal-efr32/em_leuart.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_rmu.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_rmu.d" -MT"hal-efr32/em_rmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_rtc.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_rtc.d" -MT"hal-efr32/em_rtc.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_rtcc.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rtcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_rtcc.d" -MT"hal-efr32/em_rtcc.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_system.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_system.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_system.d" -MT"hal-efr32/em_system.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_timer.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_timer.d" -MT"hal-efr32/em_timer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_usart.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_usart.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/em_usart.d" -MT"hal-efr32/em_usart.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/gpiointerrupt.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/gpiointerrupt/src/gpiointerrupt.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/gpiointerrupt.d" -MT"hal-efr32/gpiointerrupt.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/hal_common.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/hal/hal_common.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/hal_common.d" -MT"hal-efr32/hal_common.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/hal_efr.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/hal/efr32/hal_efr.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/hal_efr.d" -MT"hal-efr32/hal_efr.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/retargetio.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/retargetio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/retargetio.d" -MT"hal-efr32/retargetio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/retargetserial.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/retargetserial.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/retargetserial.d" -MT"hal-efr32/retargetserial.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/rtcdriver.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/rtcdrv/src/rtcdriver.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/rtcdriver.d" -MT"hal-efr32/rtcdriver.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/ustimer.o: C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/ustimer/src/ustimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb '-DEFR32FG1P133F256GM48=1' '-DBOARD_BRD4250A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' -IC:/Users/oldcat/SimplicityStudio/v3_workspace/rangetest -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//apps/rangetest" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/spidrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/uartdrv/inc" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32FG1_BRD4250A/config" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"C:/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32FG1P/Include" -Os -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -std=gnu99 -MMD -MP -MF"hal-efr32/ustimer.d" -MT"hal-efr32/ustimer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


